export type CourseType = {
  name: string;
  code: string;
  type: "전체" | "기본소양" | "전공기반" | "공학전공" | "교직";
  year: "1학년" | "2학년" | "3학년" | "4학년" | "전학년";
  semester: "전학기" | "1학기" | "2학기";
  credit: "전체" | "1학점" | "2학점" | "3학점" | "4학점" | "5학점" | "6학점";
  required: "전체" | "필수" | "선택";
  design: "전체" | "설계" | "비설계";
};

export const courseData: CourseType[] = [
  {
    name: "논리와 비판적 사고",
    code: "CLTR0045",
    type: "기본소양",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "소셜네트워크",
    code: "CLTR0264",
    type: "기본소양",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "수학1",
    code: "CLTR0211",
    type: "전공기반",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "물리학1",
    code: "CLTR0213",
    type: "전공기반",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "물리학실험1",
    code: "CLTR0223",
    type: "전공기반",
    year: "1학년",
    semester: "1학기",
    credit: "1학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "컴퓨팅사고와 SW코딩",
    code: "COMP0453",
    type: "공학전공",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "컴퓨터학개론",
    code: "ITEC0201",
    type: "공학전공",
    year: "1학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "실용화법",
    code: "CLTR0003",
    type: "기본소양",
    year: "1학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "대학글쓰기",
    code: "CLTR0205",
    type: "기본소양",
    year: "1학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "이산수학",
    code: "COME0301",
    type: "전공기반",
    year: "1학년",
    semester: "2학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "프로그래밍기초",
    code: "COMP0204",
    type: "전공기반",
    year: "1학년",
    semester: "2학기",
    credit: "6학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "기초창의공학설계",
    code: "COMP0205",
    type: "전공기반",
    year: "1학년",
    semester: "2학기",
    credit: "3학점",
    required: "필수",
    design: "설계",
  },
  {
    name: "미래산업과 직업선택",
    code: "CLTR0689",
    type: "기본소양",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "자바프로그래밍",
    code: "COMP0217",
    type: "공학전공",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "자료구조",
    code: "COME0331",
    type: "공학전공",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "자료구조응용",
    code: "COMP0216",
    type: "공학전공",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "오토마타 및 형식언어",
    code: "COMP0315",
    type: "공학전공",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "논리회로",
    code: "ELEC0247",
    type: "공학전공",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "확률 및 통계",
    code: "COME0311",
    type: "전공기반",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "데이터과학기초",
    code: "ITEC0419",
    type: "전공기반",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "선형대수",
    code: "MTED0231",
    type: "전공기반",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "소프트웨어설계",
    code: "COMP0224",
    type: "공학전공",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "설계",
  },
  {
    name: "디지털설계및실험",
    code: "COMP0225",
    type: "공학전공",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "설계",
  },
  {
    name: "컴퓨터구조",
    code: "COMP0411",
    type: "공학전공",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "시스템프로그래밍",
    code: "ELEC0462",
    type: "공학전공",
    year: "2학년",
    semester: "2학기",
    credit: "3학점",
    required: "필수",
    design: "설계",
  },
  {
    name: "알고리즘1",
    code: "COMP0319",
    type: "공학전공",
    year: "3학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "운영체제",
    code: "COMP0312",
    type: "공학전공",
    year: "3학년",
    semester: "1학기",
    credit: "3학점",
    required: "필수",
    design: "비설계",
  },
  {
    name: "네트워크프로그래밍",
    code: "EECS0312",
    type: "공학전공",
    year: "3학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "일반생명과학1",
    code: "CLTR246",
    type: "전공기반",
    year: "2학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "데이타베이스",
    code: "COMP0322",
    type: "공학전공",
    year: "3학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "종합설계프로젝트1",
    code: "ITEC0401",
    type: "공학전공",
    year: "3학년",
    semester: "2학기",
    credit: "4학점",
    required: "필수",
    design: "설계",
  },
  {
    name: "모바일앱프로그래밍1",
    code: "COMP0328",
    type: "공학전공",
    year: "3학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "컴퓨터망",
    code: "COMP0414",
    type: "공학전공",
    year: "4학년",
    semester: "1학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "종합설계프로젝트2",
    code: "ITEC0402",
    type: "공학전공",
    year: "4학년",
    semester: "1학기",
    credit: "4학점",
    required: "필수",
    design: "설계",
  },
  {
    name: "고급문제해결",
    code: "ITEC0415",
    type: "공학전공",
    year: "4학년",
    semester: "1학기",
    credit: "4학점",
    required: "선택",
    design: "비설계",
  },
  {
    name: "대규모병렬컴퓨팅",
    code: "ITEC0418",
    type: "공학전공",
    year: "4학년",
    semester: "2학기",
    credit: "3학점",
    required: "선택",
    design: "비설계",
  },
];
